---
galaxy_info:
  author: George Miroshnykov
  description: >
    Given a list of GitHub usernames, this Ansible role downloads their
    SSH public keys from GitHub and adds them to ~/.ssh/authorized_keys
  company: Rebbix
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system
